//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RasporedApp.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Table
    {
        public decimal         Id { get; set; }
        public string          DAN { get; set; }
        public string          PREDMET { get; set; }
        public System.TimeSpan VRIJEME { get; set; }     
        public string          PROFESOR { get; set; }
        public string          NAPOMENE { get; set; }
    }
}
